# Generated by Django 4.0.3 on 2022-04-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.IntegerField(choices=[(1, 'Cat'), (2, 'Dog')])),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Unknown')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.animal', verbose_name='Animal Details')),
            ],
        ),
    ]
