# Generated by Django 4.0.3 on 2022-04-08 11:26

from django.db import migrations, models
import health_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, upload_to=health_app.models.Pet.pet_photo_file_name),
        ),
    ]
