# Generated by Django 4.0.3 on 2022-04-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_alter_animal_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Date of Birth'),
        ),
    ]
