# Generated by Django 4.0.3 on 2022-04-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_alter_animal_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health_app.animal', verbose_name='Animal Details'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_app.medicalevent'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_visits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_app.vetvisit'),
        ),
    ]
