# Generated by Django 4.0.3 on 2022-04-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='medical_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.medicalevent'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vet_visits',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.vetvisit'),
        ),
    ]
