# Generated by Django 4.0.3 on 2022-04-09 19:26

import apps.pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='default_pet_photos/31.jpg', upload_to=apps.pets.models.Pet.pet_photo_file_name),
        ),
    ]
