# Generated by Django 4.0.3 on 2022-04-10 15:00

import apps.pets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pets', '0002_alter_pet_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='pet',
            name='medical_event',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vet_visits',
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default=apps.pets.models.Pet.default_pet_photo, upload_to=apps.pets.models.Pet.pet_photo_file_name),
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('petevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.petevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pets.petevent',),
        ),
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('petevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.petevent')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pets.petevent',),
        ),
        migrations.DeleteModel(
            name='MedicalEvent',
        ),
        migrations.DeleteModel(
            name='VetVisit',
        ),
        migrations.AddField(
            model_name='petevent',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
