# Generated by Django 4.0.3 on 2022-04-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_petevent_remove_pet_medical_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petevent',
            name='title',
        ),
    ]
